version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "23:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "maintenance"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "23:15"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "maintenance"
    commit-message:
      prefix: "chore(actions)"
